### ISSUE TITLE
Cannot start the server

### ISSUE THREAD

**Issue by dipankarkghosal** [chrisneave/FakeMinder#5]
I cannot start the server with the default config.json provided . 
fakeminder start config1.json
fakeminder info fakeminder Starting FakeMinder server using configuration file config.json.
/usr/local/lib/node_modules/fakeminder/lib/config.js:37
  self.proxy_pass = config.proxy_pass;
                           ^

TypeError: Cannot read property 'proxy_pass' of undefined
    at new UpstreamApp (/usr/local/lib/node_modules/fakeminder/lib/config.js:37:28)
    at Config.upstreamApp (/usr/local/lib/node_modules/fakeminder/lib/config.js:82:12)
    at Object.module.exports.start (/usr/local/lib/node_modules/fakeminder/lib/server.js:40:31)
    at Command.<anonymous> (/usr/local/lib/node_modules/fakeminder/bin/fakeminder:28:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/fakeminder/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:209:13)
    at Command.parseArgs (/usr/local/lib/node_modules/fakeminder/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/local/lib/node_modules/fakeminder/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/fakeminder/bin/fakeminder:44:9)

**Comment by dipankarkghosal** [comment]
figured out .. used -c option to pass config and it worked

**Comment by chrisneave** [comment]
Glad you figured it out @dipankarkghosal ! It looks like the instructions in the README.md for starting the server are wrong - I'll update them to avoid confusing others too.
